name: Creating Spring boot native
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # need this for OIDC
      contents: read
      
    steps:

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Maven and Buildpacks
        run: mvn clean spring-boot:build-image -Dspring-boot.build-image.imageName=sbnat:latest -s settings.xml

      - name: Set project version as environment variable
        run: echo "PROJECT_VERSION=1.0.0" >> $GITHUB_ENV
          
      - name: Tag and push image
        env:
          ECR_REGISTRY: ghcr.io
          ECR_REPOSITORY: sbnat
          IMAGE_TAG: ${{ env.PROJECT_VERSION }}
        run: |
          # Build a docker container and push it to ECR so that it can be deployed to ECS.
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} $ECR_REGISTRY
          docker tag docker.io/library/rest-service-complete:0.0.1-SNAPSHOT $ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/c3s4rfred/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REPOSITORY:$IMAGE_TAG"
